/*
 * GNOME::base
 *  
 */
interface base {
	/**
	 * ref:
	 *
	 * increments the reference count
	 */
	oneway void ref ();

	/**
	 * unref:
	 * 
	 * decrements the reference count
	 */
	oneway void unref ();
};
