#ifndef __GNOME_EDITOR_IDL__
#define __GNOME_EDITOR_IDL__

#if defined(__ORBIT_IDL__)
%{
#pragma include_defs gnome-editor.h
%}
#pragma inhibit push
#endif

#include <gnome-file.idl>

module GNOME {

	/* kept this because it looks cleaner (IMHO) when you use this */
	interface EditorFactory : GNOME::FileFactory {
	};

	interface Editor : GNOME::File {
		void insert (in string              new);
		void delete (in unsigned long       charcount);
		void replace (in string             regexp,
		              in string             newstring,
						  in GNOME::SEEKFROM    whence,
		              in GNOME::SearchOption flags) raises (NotFound);
	};
};

#if defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif /* __GNOME_EDITOR_IDL__ */
