/*
 * gnome-factory.idl: Basic object factory interface, based on CORBA
 * LifeCycle version
 */

#ifndef __LIBGNORBA_COMPILATION
%{
#pragma include_defs libgnorba/gnome-factory.h
%}
#pragma inhibit push
#endif

module GNOME {
	typedef sequence<string> stringlist;

	interface GenericFactory {
		exception CannotActivate { };
		boolean supports(in string obj_goad_id);

		Object create_object(in string goad_id, in stringlist params)
			raises(CannotActivate);
	};
};

#ifndef __LIBGNORBA_COMPILATION
#pragma inhibit pop
#endif