#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs libgnorba/GnomeObject.h
%}
#pragma inhibit push
#endif

module GNOME {
	interface obj {
		/**
		 * ref:
		 *
		 * increments the reference count
		 */
		oneway void ref ();
		/**
		 * unref:
		 * 
		 * decrements the reference count
		 */
		oneway void unref ();
		
		Object query_interface (in string repoid);
	};
};

#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif
