/*
 * gnome-factory.idl: Basic object factory interface, based on CORBA
 * LifeCycle version
 */
module GNOME {
	typedef sequence<string> stringlist;

	interface GenericFactory {
		exception CannotActivate { };
		boolean supports(in string obj_goad_id);

		Object create_object(in string goad_id, in stringlist params)
			raises(CannotActivate);
	};
};
