/*
 * gnome-factory.idl: Basic object factory interface, based on CORBA
 * LifeCycle version
 */

#ifndef __REXEC_IDL__
#define __REXEC_IDL__

#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs libgnomeui/gnome-corba-rexec.h
%}
#pragma inhibit push
#endif

#if defined(__ORBIT_IDL__)
%{
#pragma include_defs liboaf/oaf-factory.h
%}
#pragma inhibit push
module GNOME {
  typedef sequence<string> stringlist;
};
#pragma inhibit pop
#endif

module GNOME {
  interface RemoteExecution {
    exception POSIXError { long unportable_errno; string errstr; };
    /* Returns PID upon success. */
    long execVectorEnvPath(in stringlist argv, in stringlist envp);
  };
};

#if !defined(__LIBGNORBA_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif
